inputs:
  port:
    description: 'Port for node application to run'
    default: 1010
  enviroment:
    description: 'Enviroment for node aplication'
    default: 'DEV'

runs:
  using: "composite"
  steps:
    - name: Deploy to Environment
      run: echo Deploying to ${{ inputs.enviroment }} environment ..
      shell: cmd
    
    - name: Install dependencies
      working-directory: course-js-api-framework
      run: npm install
      shell: cmd

    - name: Install pm2
      working-directory: course-js-api-framework
      run: npm install -g pm2
      shell: cmd

    - name: Delete services
      working-directory: python-greetings
      run: pm2 delete greetings-app-${{ inputs.enviroment }} || true
      shell: cmd

    - name: Start services
      working-directory: python-greetings
      run: pm2 start app.py --name greetings-app-${{ inputs.enviroment }} -- --port ${{ inputs.port }}
      shell: cmd