inputs:
  port:
    description: 'Port for node application to run'
    default: 1010
  enviroment:
    description: 'Enviroment for node aplication'
    default: 'DEV'

runs:
  using: "composite"
  steps:
    - name: Deploy to Environment
      run: echo Deploying to ${{ inputs.enviroment }} environment ..
      shell: cmd
    
    - name: Install dependencies
      run: npm install
      shell: cmd

    - name: Install pm2
      run: npm install -g pm2
      shell: cmd

    - name: Delete services
       run: pm2 delete greetings-app-${{ inputs.enviroment }} || set "errorlevel=0"
       shell: cmd

    - name: Start services
      run: pm2 start -n ${{ inputs.enviroment }} index.js -- ${{ inputs.port }}
      shell: cmd