inputs:
  port:
    description: 'Port for node application to run'
    default: 1010
  enviroment:
    description: 'Enviroment for node aplication'
    default: 'DEV'
runs:
  using: "composite"
  steps:
    - name: Print output
      run: echo Deplyment to ${{ inputs.enviroment }} has started ..
      shell: cmd
    
    - name: Install dependencies
      run: npm install
      shell: cmd

    - name: Install pm2
      run: sudo npm install -g pm2
      shell: cmd

    - name: Delete services
       run: pm2 delete ${{ inputs.enviroment }}
       shell: cmd

    - name: Start services
      run: pm2 start -n ${{ inputs.enviroment }} index.js -- ${{ inputs.port }}
      shell: cmd

    # - name: Check services
    #   run: pm2 list
    #   shell: cmd
