name: CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3.5.2

      - uses: actions/checkout@v3.5.2
        with:
          repository: ligabuce/python-greetings
          path: python-greetings

      - name: Install Pip Dependencies
        working-directory: python-greetings
        run : |
          pip install -r requirements.txt
          echo Installing all required dependencies..

  deploy-to-dev:
    runs-on: self-hosted
    needs: [install-pip-deps]

    steps:
      - name: Access repository
        uses: actions/checkout@v3.5.2

      - name: Clone python-greetings
        uses: actions/checkout@v3.5.2
        with:
          repository: ligabuce/python-greetings
          path: python-greetings

      - name: Clone course-js-api-framework
        uses: actions/checkout@v3.5.2
        with:
          repository: ligabuce/course-js-api-framework
          path: course-js-api-framework

      - name: Deploy pm2 actions with actions.yml file
        uses: ./.github/actions/deploy
        with:
          port: 7001
          enviroment: 'dev'
          
  tests-on-dev:
    runs-on: self-hosted
    needs: [deploy-to-dev]
    steps:
      - name: Access repository
        uses: actions/checkout@v3.5.2

      - name: Clone course-js-api-framework
        uses: actions/checkout@v3.5.2
        with:
          repository: ligabuce/course-js-api-framework
          path: course-js-api-framework-path
      
      - name: Run Test with npm
        uses: ./.github/actions/test
        with:
          enviroment: 'dev'

  deploy-to-staging:
    runs-on: self-hosted
    needs: [tests-on-dev]
    steps:
      - name: Access repository
        uses: actions/checkout@v3.5.2

      - name: Clone python-greetings
        uses: actions/checkout@v3.5.2
        with:
          repository: ligabuce/python-greetings
          path: python-greetings

      - name: Clone course-js-api-framework
        uses: actions/checkout@v3.5.2
        with:
          repository: ligabuce/course-js-api-framework
          path: course-js-api-framework

      - name: Deploy pm2 actions with actions.yml file
        uses: ./.github/actions/deploy
        with:
          port: 7002
          enviroment: 'staging'

  tests-on-staging:
    runs-on: self-hosted
    needs: [deploy-to-staging]
    steps:
      - name: Access repository
        uses: actions/checkout@v3.5.2

      - name: Clone course-js-api-framework
        uses: actions/checkout@v3.5.2
        with:
          repository: ligabuce/course-js-api-framework
          path: course-js-api-framework-path
      
      - name: Run Test with npm
        uses: ./.github/actions/test
        with:
          enviroment: 'staging'

  deploy-to-preprod:
    runs-on: self-hosted
    needs: [tests-on-staging]
    steps:
      - name: Access repository
        uses: actions/checkout@v3.5.2

      - name: Clone python-greetings
        uses: actions/checkout@v3.5.2
        with:
          repository: ligabuce/python-greetings
          path: python-greetings

      - name: Clone course-js-api-framework
        uses: actions/checkout@v3.5.2
        with:
          repository: ligabuce/course-js-api-framework
          path: course-js-api-framework

      - name: Deploy pm2 actions with actions.yml file
        uses: ./.github/actions/deploy
        with:
          port: 7003
          enviroment: 'preprod'

  tests-on-preprod:
    runs-on: self-hosted
    needs: [deploy-to-preprod]
    steps:
      - name: Access repository
        uses: actions/checkout@v3.5.2

      - name: Clone course-js-api-framework
        uses: actions/checkout@v3.5.2
        with:
          repository: ligabuce/course-js-api-framework
          path: course-js-api-framework-path
      
      - name: Run Test with npm
        uses: ./.github/actions/test
        with:
          enviroment: 'preprod'

  deploy-to-prod:
    runs-on: self-hosted
    needs: [tests-on-preprod]
    steps:
      - name: Access repository
        uses: actions/checkout@v3.5.2

      - name: Clone python-greetings
        uses: actions/checkout@v3.5.2
        with:
          repository: ligabuce/python-greetings
          path: python-greetings

      - name: Clone course-js-api-framework
        uses: actions/checkout@v3.5.2
        with:
          repository: ligabuce/course-js-api-framework
          path: course-js-api-framework

      - name: Deploy pm2 actions with actions.yml file
        uses: ./.github/actions/deploy
        with:
          port: 7004
          enviroment: 'prod'

  tests-on-prod:
    runs-on: self-hosted
    needs: [deploy-to-prod]
    steps:
      - name: Access repository
        uses: actions/checkout@v3.5.2

      - name: Clone course-js-api-framework
        uses: actions/checkout@v3.5.2
        with:
          repository: ligabuce/course-js-api-framework
          path: course-js-api-framework-path
      
      - name: Run Test with npm
        uses: ./.github/actions/test
        with:
          enviroment: 'proc'